# Generated by Django 6.0 on 2026-02-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationlog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("low_stock", "Low Stock Alert"),
                    ("price_anomaly", "Price Anomaly Detected"),
                    ("production_complete", "Production Run Completed"),
                    ("sale_complete", "Sale Completed"),
                    ("eod_closing", "End of Day Closing"),
                    ("stock_adjustment", "Stock Adjustment Made"),
                    ("purchase_created", "Purchase Recorded"),
                    ("user_created", "New User Created"),
                    ("user_login", "User Login"),
                    ("factory_reset", "Factory Reset Performed"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("low_stock", "Low Stock Alert"),
                    ("price_anomaly", "Price Anomaly Detected"),
                    ("production_complete", "Production Run Completed"),
                    ("sale_complete", "Sale Completed"),
                    ("eod_closing", "End of Day Closing"),
                    ("stock_adjustment", "Stock Adjustment Made"),
                    ("purchase_created", "Purchase Recorded"),
                    ("user_created", "New User Created"),
                    ("user_login", "User Login"),
                    ("factory_reset", "Factory Reset Performed"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
