# Generated by Django 6.0 on 2025-12-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_full_name_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='push_notifications_enabled',
            field=models.BooleanField(default=True, help_text='Receive push notifications'),
        ),
    ]
