# Generated by Django 6.0 on 2025-12-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_push_notifications_enabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="push_notifications_enabled",
            field=models.BooleanField(
                default=False, help_text="Receive push notifications"
            ),
        ),
    ]
