# Generated by Django 6.0 on 2026-02-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_shift_template_unique_start_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverecord',
            name='leave_type',
            field=models.CharField(choices=[('sick', 'Sick Leave'), ('annual', 'Annual Leave'), ('holiday', 'Holiday Leave'), ('other', 'Other Leave')], max_length=20),
        ),
    ]
