# Generated by Django 6.0 on 2025-12-13 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='is_composite',
        ),
    ]
