# Generated by Django 6.0 on 2026-02-04 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_ingredient_is_composite'),
        ('treasury', '0003_rename_treasury_ba_created_7c0f9b_idx_treasury_ba_created_156ff8_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='expense',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase', to='treasury.expense'),
        ),
    ]
