# Generated by Django 6.0 on 2026-08-03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0004_purchase_expense"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="kitchen_stock",
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name="KitchenTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=10)),
                (
                    "storehouse_balance_before",
                    models.DecimalField(decimal_places=3, max_digits=10),
                ),
                (
                    "kitchen_balance_before",
                    models.DecimalField(decimal_places=3, max_digits=10),
                ),
                ("notes", models.TextField(blank=True)),
                ("transferred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="kitchen_transfers",
                        to="inventory.ingredient",
                    ),
                ),
                (
                    "transferred_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-transferred_at"]},
        ),
    ]
