# Generated by Django 6.0 on 2026-02-04 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0002_bankaccount_logo'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='banktransaction',
            new_name='treasury_ba_created_156ff8_idx',
            old_name='treasury_ba_created_7c0f9b_idx',
        ),
        migrations.RenameIndex(
            model_name='banktransaction',
            new_name='treasury_ba_account_64a7d3_idx',
            old_name='treasury_ba_account_3dbe65_idx',
        ),
        migrations.RenameIndex(
            model_name='expense',
            new_name='treasury_ex_created_92a785_idx',
            old_name='treasury_ex_created_7c6b49_idx',
        ),
        migrations.RenameIndex(
            model_name='expense',
            new_name='treasury_ex_status_ba72ab_idx',
            old_name='treasury_ex_status_ebd4b2_idx',
        ),
    ]
