# Generated by Django 6.0 on 2025-12-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bakerysettings",
            name="facebook_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="bakerysettings",
            name="facebook_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bakerysettings",
            name="instagram_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="bakerysettings",
            name="instagram_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bakerysettings",
            name="telegram_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="bakerysettings",
            name="telegram_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bakerysettings",
            name="tiktok_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="bakerysettings",
            name="tiktok_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bakerysettings",
            name="x_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="bakerysettings",
            name="x_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bakerysettings",
            name="youtube_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="bakerysettings",
            name="youtube_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
