# Generated by Django 6.0 on 2025-12-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_bakerysettings_theme_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bakerysettings',
            name='theme_color',
            field=models.CharField(default='#f2751a', help_text='Hex color code for app accent/theme color (e.g., #f2751a)', max_length=7),
        ),
    ]
