# Generated by Django 6.0 on 2026-02-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_bakerysettings_theme_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakerysettings',
            name='sync_sales_to_bank_accounts',
            field=models.BooleanField(default=False, help_text='When enabled, sales linked to payment methods update bank balances.'),
        ),
    ]
